name: "Build and release jvc"

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  unit_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test

  build_release:
    runs-on: windows-latest
    name: "Release jvc for Windows"
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable

    - uses: actions/checkout@v2
    - name: Build release binary
      run: cargo build --release

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
          
    - name: Upload binary to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/jvc.exe
        asset_name: jvc-win
        tag: ${{ steps.tag_version.outputs.new_tag }}
        overwrite: true

  build_macos_release:
    runs-on: macOS-latest
    name: "Release jvc for MacOS"
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable

    - uses: actions/checkout@v2
    - name: Build release binary
      run: cargo build --release
      env:
        LZMA_API_STATIC: "true"
    - name: Strip binary from debug symbols
      run: strip target/release/jvc
    - name: List dynamically linked libraries
      run: otool -L target/release/jvc

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload binary to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/jvc
        asset_name: jvc-macos
        tag: ${{ steps.tag_version.outputs.new_tag }}
        overwrite: true

  build_linux_binary:
    name: "Release jvc for Linux"
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - name: Build project
      run: cargo build --release
    
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
     
    - name: Upload binary to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/jvc
        asset_name: jvc-linux
        tag: ${{ steps.tag_version.outputs.new_tag }}
        overwrite: true
